/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 24 19:15:45 GMT 2026
 */

package evoSuite;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.Cell;
import ar.edu.unrc.game2048.Board.Direction;
import ar.edu.unrc.game2048.Board.Position;

import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Board_ESTest extends Board_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(987, 816);
      Board.Position board_Position1 = new Board.Position(1772, 1755);
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertEquals(1755, board_Position1.col);
      assertEquals(1772, board_Position1.row);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell(2, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = new Cell(4);
      // Undeclared exception!
      try { 
        board0.setCell(4, (-1879), cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, -1879) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Board board0 = new Board(1);
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertTrue(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = board0.getCell(2, 2);
      assertEquals(".", cell0.toString());
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = board0.getCell(0, 0);
      assertEquals(2, cell0.getValue());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        board0.setCell(2048, (-2719), cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2048, -2719) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.move((Board.Direction) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((Board) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Board board0 = new Board(468);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Board board0 = new Board();
      board0.repOK();
      assertFalse(board0.isWinningBoard());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board();
      boolean boolean0 = board0.equals(board1);
      assertFalse(boolean0);
      assertEquals(0, board1.getScore());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      Board.Direction board_Direction0 = Board.Direction.DOWN;
      board1.move(board_Direction0);
      board1.move(board_Direction0);
      boolean boolean0 = board0.equals(board1);
      assertEquals(4, board1.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      boolean boolean0 = board1.equals(board0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.equals(board0);
      assertFalse(board0.isWinningBoard());
      assertTrue(boolean0);
      assertEquals(4, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isWinningBoard();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.hasEmptyCells();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Board board0 = new Board();
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertEquals(0, board0.getScore());
      assertEquals(14, set0.size());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(650, 650);
      Board.Position board_Position1 = new Board.Position(650, 657);
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertEquals(650, board_Position1.row);
      assertFalse(board_Position1.equals((Object)board_Position0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(650, 650);
      Board.Position board_Position1 = new Board.Position((-1746), 657);
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertFalse(boolean0);
      assertEquals((-1746), board_Position1.row);
      assertEquals(657, board_Position1.col);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 0);
      Board.Position board_Position1 = new Board.Position(0, 0);
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(4, 4);
      boolean boolean0 = board_Position0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals(4, board_Position0.row);
      assertEquals(4, board_Position0.col);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 0);
      boolean boolean0 = board_Position0.equals(board_Position0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 0);
      Board.Direction board_Direction0 = Board.Direction.LEFT;
      boolean boolean0 = board_Position0.equals(board_Direction0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Board board0 = new Board();
      String string0 = board0.toString();
      assertEquals("Score: 0\n+-----+-----+-----+-----+\n|    2|     |    2|     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n", string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Board board0 = new Board(2);
      Board.Direction board_Direction0 = Board.Direction.RIGHT;
      boolean boolean0 = board0.equals(board_Direction0);
      assertFalse(boolean0);
      assertEquals(2, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals(0, board0.getScore());
      assertFalse(board0.isWinningBoard());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Random.setNextRandom((-1239));
      Board board0 = new Board();
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Board board0 = new Board();
      Board.Direction board_Direction0 = Board.Direction.RIGHT;
      board0.move(board_Direction0);
      boolean boolean0 = board0.move(board_Direction0);
      assertEquals(4, board0.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Board board0 = new Board();
      Board.Direction board_Direction0 = Board.Direction.DOWN;
      board0.move(board_Direction0);
      board0.move(board_Direction0);
      int int0 = board0.getScore();
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Board board0 = new Board(1);
      Board.Direction board_Direction0 = Board.Direction.UP;
      boolean boolean0 = board0.move(board_Direction0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.isFull();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isFull();
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isLosingBoard();
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertFalse(boolean0);
      assertFalse(board0.isWinningBoard());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.isLosingBoard();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.hasEmptyCells();
      assertTrue(boolean0);
      assertEquals(4, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell(2, 2048);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2, 2048) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell(1, (-2215));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (1, -2215) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Board board0 = new Board(2);
      // Undeclared exception!
      try { 
        board0.getCell((-15), (-1112));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-15, -1112) is out of bounds for board size 2
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = new Cell(0);
      board0.setCell(0, 0, cell0);
      assertEquals(4, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Board board0 = new Board();
      Board.Direction board_Direction0 = Board.Direction.LEFT;
      boolean boolean0 = board0.move(board_Direction0);
      assertEquals(4, board0.getScore());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((-3136));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -3136
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Board board0 = new Board();
      int int0 = board0.getSize();
      assertFalse(board0.isWinningBoard());
      assertEquals(4, int0);
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Board board0 = new Board();
      board0.hashCode();
      assertEquals(4, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Board board0 = new Board();
      int int0 = board0.getScore();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(4, 2302);
      String string0 = board_Position0.toString();
      assertEquals("(4, 2302)", string0);
  }
}
